// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgymonjzzwbsqbnmvqrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNneW1vbmp6endic3Fibm12cXJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODc3MDAsImV4cCI6MjA2NTM2MzcwMH0.2cxMQrjjClg_Ox7oFkTC0zhf3SBPMgMibnq_PaqU_Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);